name: 'Webpack stats diff'
description: 'Adds a comment to your pull request with a summary of webpack stats changes between two builds'
inputs:
  percent-change-minimum:
    description: 'Report bundle size changes as significant if they exceed this percentage (0.05 = 5%)'
    required: true
    default: '.05'
  increase-label:
    description: 'The label to add to PRs that increased the size of any bundle'
    required: true
    default: '⚠️ bundle increase'
  decrease-label:
    description: 'The label to add to PRs that decreased the size of any bundle'
    required: true
    default: '🎉 bundle decrease'
  violation-label:
    description: 'The label to add to PRs that decreased the size of any bundle'
    required: true
    default: '❌ bundle budget violation'
  base-bundle-analysis-report-path:
    description: 'The path to the json webpack-bundle-analyzer report file for the base branch'
    required: true
  head-bundle-analysis-report-path:
    description: 'The path to the json webpack-bundle-analyzer report file for the head branch'
    required: true
  github-token:
    description: 'The Github token used to comment on pull requests'
    required: true
  should-block-pr-on-exceeded-budget:
    description: 'if targeted-bundles is declared, fail build if budget is exceeded for a targeted bundle'
    required: false
  skip-comment-on-no-changes:
    description: 'Skip posting PR comment when there are no significant bundle changes'
    required: false
    default: 'false'
  size-change-minimum:
    description: 'Report bundle size changes as significant if they exceed this byte amount (filters out tiny changes due to rounding)'
    required: false
    default: '2000'

runs:
  using: 'node12'
  main: 'dist/index.js'
