on: pull_request
name: Pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run: npm ci
      - name: format check
        run: npm run format-check
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: package
        run: npm run package
