on: pull_request
name: Pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run: yarn
      - name: format check
        run: yarn format-check
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: package
        run: yarn package
