on: pull_request
name: Pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run: npm ci
      - name: format check
        run: npm run format-check
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: package
        run: npm run package
      - name: check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Uncommitted changes detected after packaging:"
            git status --porcelain
            echo ""
            echo "Please run 'npm run package' and commit the changes."
            exit 1
          else
            echo "✅ No uncommitted changes after packaging"
          fi
